### PR TITLE
Remove spellcheck component

### PR DESCRIPTION
**Pull request by mcritchlow**
Changes included:
- Remove spellcheck related fields from schema.xml (static and dynamic) in all environments
- Remove spellcheck components from solr_config.xml in all environments

Note this will pair with a damspas PR that is forthcoming.

@ucsdlib/developers and @rstanonik please review

### CODE REVIEW

**Comment by lsitu** [comment]
👍

**Comment by VivianChu** [comment]
👍

**Comment by mcritchlow** [comment]
@ucsdlib/developers @rstanonik if this looks ok would someone mind merging so we can be ready to eventually deploy this to the various enviornments for testing?

**Comment by hweng** [comment]
:+1:

**Pull request merged**
